services:
  - docker:dind

variables:
    LSWS: 6.0.12
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay

lsphp53:
  variables:
    PHP: lsphp53
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp54:
  variables:
    PHP: lsphp54
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp55:
  variables:
    PHP: lsphp55
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp56:
  variables:
    PHP: lsphp56
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp70:
  variables:
    PHP: lsphp70
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp71:
  variables:
    PHP: lsphp71
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp72:
  variables:
    PHP: lsphp72
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp73:
  variables:
    PHP: lsphp73
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp74:
  variables:
    PHP: lsphp74
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp80:
  variables:
    PHP: lsphp80
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd

lsphp81:
  variables:
    PHP: lsphp81
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP} --push
  tags:
    - cllpsd
