services:
  - docker:dind

variables:
    LSWS: 6.0.12
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay

lsphp53:
  variables:
    INTERPRETER: lsphp53
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp54:
  variables:
    INTERPRETER: lsphp54
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp55:
  variables:
    INTERPRETER: lsphp55
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp56:
  variables:
    INTERPRETER: lsphp56
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp70:
  variables:
    INTERPRETER: lsphp70
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  

lsphp71:
  variables:
    INTERPRETER: lsphp71
    OS: centos7
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp72:
  variables:
    INTERPRETER: lsphp72
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp73:
  variables:
    INTERPRETER: lsphp73
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp74:
  variables:
    INTERPRETER: lsphp74
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp80:
  variables:
    INTERPRETER: lsphp80
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lsphp81:
  variables:
    INTERPRETER: lsphp81
    OS: almalinux8
  stage: build
  image: docker:latest
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker buildx build . --file docker/Dockerfile.${OS} --tag ${DOCKER_USER}/${DOCKER_REPO}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  tags:
    - cllpsd
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
