name: Build LSWS Docker

on:
  push:
    branches: [ "main" ]
  
env:
      LSWS: 6.0.12

jobs:
  lsphp53:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp53

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push

  lsphp54:
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp54

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image  
      run: |
        docker buildx build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push

  lsphp55:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp55

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image   
      run: |
        docker buildx build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push

  lsphp56:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp56

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push

  lsphp70:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp70

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
      
  lsphp71:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp71

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
       
  lsphp72:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp72

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
      
  lsphp73:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp73

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
  
  lsphp74:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp74

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
        
  lsphp80:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp80

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push
        
  lsphp81:      
    runs-on: self-hosted
    env:
        INTERPRETER: lsphp81

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker buildx buildx build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${INTERPRETER} --build-arg LSWS_VERSION=${LSWS} --build-arg INTERPRETER=${INTERPRETER} --push

 
