name: Build LSWS Docker

on:
  push:
    branches: [ "main" ]

jobs:
  env:
      LSWS: 6.0.12

  prepare:
    

    runs-on: self-hosted

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

  build-lsphp70:
    env:
      PHP: lsphp70

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  build-lsphp71:
    env:
      PHP: lsphp71

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  build-lsphp72:
    env:
      PHP: lsphp72

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  build-lsphp73:
    env:
      PHP: lsphp73

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
  
   build-lsphp74:
    env:
      PHP: lsphp74

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} 
  
  build-lsphp80:
    env:
      PHP: lsphp80

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}  
  
  build-lsphp81:
    env:
      PHP: lsphp81

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}