name: Build LSWS Docker

on:
  push:
    branches: [ "main" ]
  
env:
      LSWS: 6.0.12

jobs:
  lsphp53:      
    runs-on: self-hosted
    env:
        PHP: lsphp53

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  lsphp54:
    runs-on: self-hosted
    env:
        PHP: lsphp54

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image  
      run: |
        docker build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  lsphp55:      
    runs-on: self-hosted
    env:
        PHP: lsphp55

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build Docker image   
      run: |
        docker build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  lsphp56:      
    runs-on: self-hosted
    env:
        PHP: lsphp56

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

  lsphp70:      
    runs-on: self-hosted
    env:
        PHP: lsphp70

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.centos7 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp71:      
    runs-on: self-hosted
    env:
        PHP: lsphp71

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp72:      
    runs-on: self-hosted
    env:
        PHP: lsphp72

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp73:      
    runs-on: self-hosted
    env:
        PHP: lsphp73

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp74:      
    runs-on: self-hosted
    env:
        PHP: lsphp74

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp80:      
    runs-on: self-hosted
    env:
        PHP: lsphp80

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}
        
  lsphp81:      
    runs-on: self-hosted
    env:
        PHP: lsphp81

    steps:
    - name: Cleaning Operation
      run : sudo find ${{ github.workspace }}/. -name . -o -prune -exec rm -rf -- {} + || true
      
    - name: checkout repo
      uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker image
      run: |
        docker build . --file docker/Dockerfile.almalinux8 --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP} --build-arg LSWS_VERSION=${LSWS} --build-arg PHP_VERSION=${PHP}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO}}:${LSWS}-${PHP}

 
